name: Build Flutter for Web

on:
  push:
    paths:
      - "apps/flutter-app"

jobs:
  build-web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Install dependencies
        working-directory: ./apps/flutter-app
        run: flutter pub get
      - name: Run tests
        working-directory: ./apps/flutter-app
        run: flutter test
      - name: Build web
        working-directory: ./apps/flutter-app
        run: flutter build web
