name: Build Flutter for Web

on: push

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-web:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Install dependencies
        working-directory: ./apps/flutter-app
        run: flutter pub get
      - name: Run tests
        working-directory: ./apps/flutter-app
        run: flutter test
      - name: Build web
        working-directory: ./apps/flutter-app
        run: flutter build web
      ## Deploy to GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: "./apps/flutter-app/build/web"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
